name = "smart-plug"
main = "src/index.js"
compatibility_date = "2025-10-23"

# Compatibility flags for Node.js compatibility
compatibility_flags = ["nodejs_compat_v2"]

# Bind environment variables
[vars]
NODE_ENV = "production"
TELEGRAM_BOT_TOKEN = "5976108869:AAHFHnaws69eThgoVNi2SafXiAWKPZScauQ"
TELEGRAM_BOT_CHAT_ID = "-1001729031870"

# For development
[env.dev]
name = "smart-plug-dev"

[env.dev.vars]
NODE_ENV = "development"
TELEGRAM_BOT_TOKEN = "6065682184:AAGj99qRP9AlXt5xp3zvaFuEzTy1NaBmSOQ"
TELEGRAM_BOT_CHAT_ID = "-1003261274470"

# Build configuration
[build]
command = ""

# Assets configuration for static files
#[site]
#bucket = "./public"

# Observability
[observability]
enabled = true

# Cron Triggers - runs every 7 minutes
[triggers]
crons = ["*/7 * * * *"]

